### ISSUE TITLE
[Request] ConllU to Conll09 German

### ISSUE THREAD

**Issue by Tooa** [coastalcph/ud-conversion-tools#1]
Hi :wave:,

it would be nice, if you could enhance your `CoNLLReader()` with a `write_conll_2009` method. Maybe, I can contribute such a method in a pull request if you are interested. 

It should be enough to define a `CONLL09_COLUMNS` array and generalize from the existing `write_conll_2009` method like `write_conll_format` with the respective columns array as parameter. What do you think?

**Comment by hectormartinez** [comment]
Dear Uli, we are currently refactoring the code to add more options, and we
can certainly add a Conll2009 writer. Thanks for the suggestion and stay
tuned!

2015-12-11 0:23 GMT+01:00 Uli Fahrer notifications@github.com:

**Comment by Tooa** [comment]
Closing this issue as it is not relevant to me anymore.
